name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        default: main
        type: string

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main

  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main
    secrets: inherit
    permissions:
      contents: read
      security-events: write
      actions: read


  lint-scss:
    name: Lint SCSS
    uses: ./.github/workflows/lintscss.yml

  lint-javascript:
    name: Lint JavaScript
    uses: ./.github/workflows/lintjs.yml

  lint-prettier:
    name: Prettier
    uses: ./.github/workflows/lintprettier.yml

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  lint-erb:
    name: Lint ERB
    uses: ./.github/workflows/linterb.yml

  test-javascript:
    name: Test JavaScript
    uses: alphagov/govuk-infrastructure/.github/workflows/jasmine.yml@main
    with:
      useWithRails: true